// OTP
export const ADMIN_SEND_OTP_REQUEST = 'ADMIN_SEND_OTP_REQUEST';
export const ADMIN_SEND_OTP_SUCCESS = 'ADMIN_SEND_OTP_SUCCESS';
export const ADMIN_SEND_OTP_FAIL = 'ADMIN_SEND_OTP_FAIL';

// OTP Verify
export const ADMIN_VERIFY_OTP_REQUEST = 'ADMIN_VERIFY_OTP_REQUEST';
export const ADMIN_VERIFY_OTP_SUCCESS = 'ADMIN_VERIFY_OTP_SUCCESS';
export const ADMIN_VERIFY_OTP_FAIL = 'ADMIN_VERIFY_OTP_FAIL';

// Signup
export const ADMIN_SIGNUP_REQUEST = 'ADMIN_SIGNUP_REQUEST';
export const ADMIN_SIGNUP_SUCCESS = 'ADMIN_SIGNUP_SUCCESS';
export const ADMIN_SIGNUP_FAIL = 'ADMIN_SIGNUP_FAIL';
