// actionTypes.js

export const CREATE_CHAT_ROOM_REQUEST = 'CREATE_CHAT_ROOM_REQUEST';
export const CREATE_CHAT_ROOM_SUCCESS = 'CREATE_CHAT_ROOM_SUCCESS';
export const CREATE_CHAT_ROOM_FAIL = 'CREATE_CHAT_ROOM_FAIL';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const GET_MESSAGES_REQUEST = 'GET_MESSAGES_REQUEST';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL';
export const SEND_MESSAGE_OPTIMISTIC = 'SEND_MESSAGE_OPTIMISTIC';

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const DELETE_MESSAGE_SOCKET = 'DELETE_MESSAGE_SOCKET';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';