export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL    = 'GET_USERS_FAIL';
export const GET_ADMIN_FAIL    = 'GET_ADMIN_FAIL';
export const GET_ADMIN_REQUEST    = 'GET_ADMIN_REQUEST';
export const GET_ADMIN_SUCCESS    = 'GET_ADMIN_SUCCESS';
export const UPDATE_EMPLOYEE_REQUEST    = 'UPDATE_EMPLOYEE_REQUEST';
export const UPDATE_EMPLOYEE_SUCCESS    = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_FAIL    = 'UPDATE_EMPLOYEE_FAIL';
export const GET_SINGLE_USERS_SUCCESS    = 'GET_SINGLE_USERS_SUCCESS';

